"""empty message

Revision ID: 27a2390d37bb
Revises: c8594756235c
Create Date: 2021-11-26 18:42:05.528132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a2390d37bb'
down_revision = 'c8594756235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender', sa.Integer(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender', sa.Integer(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'sender')
    # ### end Alembic commands ###
