"""empty message

Revision ID: 15d724a99f60
Revises: e3b96a4a3b04
Create Date: 2021-11-18 17:43:53.793216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d724a99f60'
down_revision = 'e3b96a4a3b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('comments', 'createdAt')
    # ### end Alembic commands ###
