"""empty message

Revision ID: d0ad92f9851e
Revises: 27a2390d37bb
Create Date: 2021-11-26 18:49:18.055146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad92f9851e'
down_revision = '27a2390d37bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender', sa.Integer(), nullable=False))
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'sender')
    # ### end Alembic commands ###
